### ISSUE TITLE
Code samples aren't running

### ISSUE THREAD

**Issue by leaky** [rnplay/rnplay-web#47] opened 2016-11-13 12:16 UTC
Whenever I visit an rnplay.org code sample and click "Tap to play", all I see is the below...?

<img width="330" alt="screen shot 2016-11-13 at 12 15 18" src="https://cloud.githubusercontent.com/assets/5213949/20245502/f5938f42-a99a-11e6-9a81-1c3e6d2552f3.png">

**Comment by jsierles** [comment] 2016-11-16 10:06
On which example are you seeing this?

**Comment by RubenSandwich** [comment] 2016-12-03 16:59
I am also seeing this problem. It happens on all code samples.

JS output is: (Besides google fonts falling to load because it's over http not https.)
application.ec3b9353.js:1 CanvasCtrl loaded
application.ec3b9353.js:1 CanvasCtrl loaded
application.ec3b9353.js:2 clientController connected
application.ec3b9353.js:2 clientController connected

**Comment by jsierles** [comment] 2016-12-03 17:22
I just tested these samples, which work fine.

https://rnplay.org/apps/icVNTA
https://rnplay.org/apps/vWGQNg

Screenshot:

http://d.pr/i/p5At

**Comment by RubenSandwich** [comment] 2016-12-03 17:27
Those one's work fine for me too.

Here was the example I was trying to load earlier:
https://rnplay.org/apps/psad7g

I have also had other examples not load on me as well. If I remember correctly all of them were using an earlier version of RN, but I'd at least expect a Red Box instead of failing silently. (If that is indeed what is happening.)

**Comment by jsierles** [comment] 2016-12-03 17:28
@brentvatne Could this be caused by the old RN require?

**Comment by palaniraja** [comment] 2016-12-17 21:11
Is there anyway to view the source of rnplay project before migrating it to Exponent based one?

Eg., I was trying to follow a [tutorial]( https://medium.com/react-native-training/react-native-navigator-navigating-like-a-pro-in-react-native-3cb1b6dc1e30#.poapxr108) but could not see the complete source linked to rnplay as it throwing 

"
Sorry
This app is no longer available.
We had to disable apps created before switching our client to use Exponent JS. Sorry about that!
"

**Comment by jsierles** [comment] 2016-12-18 18:38
@palaniraja I've added a link on the 'sorry' page so you can view the original source files. Let me know if that helps!

Closing this issue for now. Feel free to open another if there are more issues.

**Closed by jsierles** 2016-12-18 18:38 UTC

**Comment by palaniraja** [comment] 2016-12-18 18:54
@jsierles  Awesome, it is helpful than the earlier state. Thank you.
